import type { UiIconName } from '@dyc/core';
import {
  Angry,
  Bed,
  Bird,
  Bone,
  Book,
  BookMarked,
  BookOpen,
  BookText,
  Brain,
  Calculator,
  Cat,
  Dog,
  Droplet,
  Egg,
  Fish,
  FlaskConical,
  Footprints,
  Frown,
  Globe,
  GraduationCap,
  Laptop,
  Laugh,
  Library,
  Lightbulb,
  Meh,
  Microscope,
  Milk,
  Music,
  Notebook,
  NotebookPen,
  NotebookText,
  Palette,
  PawPrint,
  Pencil,
  PiggyBank,
  Rabbit,
  Rat,
  Smile,
  Sparkles,
  Stethoscope,
  TestTube,
  TriangleRight,
  Turtle,
  Worm,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

// Un icono de Lucide por cada nombre de @dyc/core (lo que antes era un emoji).
const ICONS: Record<UiIconName, LucideIcon> = {
  Laugh,
  Smile,
  Meh,
  Frown,
  Angry,
  Bed,
  Sparkles,
  Dog,
  Cat,
  Rabbit,
  Rat,
  Bird,
  Fish,
  Turtle,
  Milk,
  PiggyBank,
  Egg,
  Worm,
  PawPrint,
  Bone,
  Droplet,
  Footprints,
  Stethoscope,
  Notebook,
  Book,
  BookText,
  BookMarked,
  NotebookPen,
  Brain,
  Microscope,
  Calculator,
  TriangleRight,
  Globe,
  Laptop,
  Palette,
  Music,
  FlaskConical,
  BookOpen,
  Pencil,
  Library,
  GraduationCap,
  Lightbulb,
  TestTube,
  NotebookText,
};

/** Icono de línea por nombre. Decorativo: el nombre accesible lo pone quien lo usa. */
export function UiIcon({ name, size = 20, ...rest }: { name: UiIconName } & LucideProps) {
  const Icon = ICONS[name] ?? Sparkles;
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true" focusable="false" {...rest} />;
}
